#!/bin/sh
set -e

PKG="lumpy"
VER="0.2.6"
PKG_DIR=/usr/lib/${PKG}${VER}

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/bin/${PKG} ]; then
    for pathname in ${PKG_DIR}/bin/*; do
        filename=`basename $pathname`
        update-alternatives --remove ${filename} /usr/bin/${filename}${VER}
    done
fi
